/**
 * Build demos/prosemirror.html from demo/template.html + a rollup bundle of
 * demo/main.js (which pulls in the deep-diffs plugin and ProseMirror).
 *
 * The bundle is inlined into the single HTML file so the demo stays fully
 * self-contained like its siblings — works from file://, zero network.
 *
 * Usage:  node integrations/prosemirror/build.mjs
 *
 * Requires prosemirror-* packages in node_modules (installed with
 * `npm install --no-save prosemirror-state prosemirror-view prosemirror-model
 *  prosemirror-transform prosemirror-schema-basic prosemirror-keymap
 *  prosemirror-history prosemirror-commands`).
 */

import { rollup } from 'rollup';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..');

/** Rollup config for the demo bundle (kept here, next to the sources). */
export const rollupConfig = {
  input: join(here, 'demo', 'main.js'),
  plugins: [nodeResolve({ browser: true })],
  onwarn(warning, warn) {
    // The bundle is an IIFE for inlining; circular deps inside prosemirror
    // packages are expected and harmless.
    if (warning.code === 'CIRCULAR_DEPENDENCY') return;
    warn(warning);
  }
};

const outputConfig = {
  format: 'iife',
  banner: [
    '/* Deep Diffs × ProseMirror demo bundle.',
    ' * Generated by integrations/prosemirror/build.mjs — do not edit by hand.',
    ' * Contains: integrations/prosemirror/deep-diffs-plugin.js (MIT) and',
    ' * ProseMirror (prosemirror-state/-view/-model/-transform/-schema-basic/',
    ' * -keymap/-history/-commands), MIT © Marijn Haverbeke and contributors.',
    ' */'
  ].join('\n')
};

const bundle = await rollup(rollupConfig);
const { output } = await bundle.generate(outputConfig);
await bundle.close();

let code = output[0].code;

// An inline <script> must not contain a literal "</script": escape any
// occurrence inside string/regex literals ("<\/script" is the same string).
code = code.replace(/<\/script/gi, '<\\/script');

const template = readFileSync(join(here, 'demo', 'template.html'), 'utf8');
const marker = '/*__BUNDLE__*/';
if (!template.includes(marker)) {
  throw new Error(`template.html is missing the ${marker} placeholder`);
}
const html = template.replace(marker, () => code);

const outPath = join(repoRoot, 'demos', 'prosemirror.html');
writeFileSync(outPath, html);
console.log(`Wrote ${outPath} (${(html.length / 1024).toFixed(0)} KB)`);
